In [169]:
import pandas as pd

breast_cancer = pd.read_csv('breast_cancer_survival.csv')
breast_cancer.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,20-May-18,26-Aug-18,Alive
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,26-Apr-18,25-Jan-19,Dead
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,24-Aug-18,08-Apr-20,Alive
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Nov-18,28-Jul-20,Alive
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,12-Dec-18,05-Jan-19,Alive

In [170]:
breast_cancer.count()

Age                   334
Gender                334
Protein1              334
Protein2              334
Protein3              334
Protein4              334
Tumour_Stage          334
Histology             334
ER status             334
PR status             334
HER2 status           334
Surgery_type          334
Date_of_Surgery       334
Date_of_Last_Visit    317
Patient_Status        321
dtype: int64

In [171]:
# converting features (when possible) to numerical columns

POS_NEG_FEATURES = ['ER status', 'PR status', 'HER2 status']
breast_cancer[POS_NEG_FEATURES].value_counts()

ER status  PR status  HER2 status
Positive   Positive   Negative       305
                      Positive        29
dtype: int64

In [172]:
# converting features (when possible) to numerical columns
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
for label in POS_NEG_FEATURES:
    breast_cancer[label] = label_encoder.fit_transform(breast_cancer[label])

# encoding the target feature too
breast_cancer['Patient_Status'] = label_encoder.fit_transform(breast_cancer['Patient_Status'])

breast_cancer[POS_NEG_FEATURES].value_counts()

ER status  PR status  HER2 status
0          0          0              305
                      1               29
dtype: int64

In [173]:
breast_cancer.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,0,0,0,Other,20-May-18,26-Aug-18,0
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,0,0,0,Other,26-Apr-18,25-Jan-19,1
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,0,0,0,Lumpectomy,24-Aug-18,08-Apr-20,0
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,0,0,0,Other,16-Nov-18,28-Jul-20,0
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,0,0,1,Lumpectomy,12-Dec-18,05-Jan-19,0

In [174]:
from sklearn.preprocessing import OneHotEncoder

CATEGORICAL_COLUMNS = ['Histology', 'Tumour_Stage']

onehot_encoder = OneHotEncoder()
# damn = onehot_encoder.fit_transform(breast_cancer[['Histology']])
breast_cancer['Histology'] = onehot_encoder.fit_transform(breast_cancer[['Histology']]).toarray()
breast_cancer

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.952560,2.15000,0.007972,-0.048340,II,1.0,0,0,0,Other,20-May-18,26-Aug-18,0
1,54,FEMALE,0.000000,1.38020,-0.498030,-0.507320,II,1.0,0,0,0,Other,26-Apr-18,25-Jan-19,1
2,63,FEMALE,-0.523030,1.76400,-0.370190,0.010815,II,1.0,0,0,0,Lumpectomy,24-Aug-18,08-Apr-20,0
3,78,FEMALE,-0.876180,0.12943,-0.370380,0.132190,I,1.0,0,0,0,Other,16-Nov-18,28-Jul-20,0
4,42,FEMALE,0.226110,1.74910,-0.543970,-0.390210,II,1.0,0,0,1,Lumpectomy,12-Dec-18,05-Jan-19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,59,FEMALE,0.024598,1.40050,0.024751,0.280320,II,1.0,0,0,1,Lumpectomy,15-Jan-19,27-Mar-20,0
330,41,FEMALE,0.100120,-0.46547,0.472370,-0.523870,I,1.0,0,0,1,Modified Radical Mastectomy,25-Jul-18,23-Apr-19,0
331,54,FEMALE,0.753820,1.64250,-0.332850,0.857860,II,1.0,0,0,0,Simple Mastectomy,26-Mar-19,11-Oct-19,1
332,74,FEMALE,0.972510,1.42680,-0.366570,-0.107820,II,0.0,0,0,0,Lumpectomy,26-Nov-18,05-Dec-18,0
333,66,FEMALE,0.286380,1.39980,0.318830,0.836050,II,1.0,0,0,0,Modified Radical Mastectomy,04-Feb-19,10-Aug-19,1

In [175]:
COLS_TO_DROP = ['Date_of_Surgery', 'Date_of_Last_Visit']
pd.get_dummies(breast_cancer.drop(COLS_TO_DROP, axis=1))

,Age,Protein1,Protein2,Protein3,Protein4,Histology,ER status,PR status,HER2 status,Patient_Status,Gender_FEMALE,Gender_MALE,Tumour_Stage_I,Tumour_Stage_II,Tumour_Stage_III,Surgery_type_Lumpectomy,Surgery_type_Modified Radical Mastectomy,Surgery_type_Other,Surgery_type_Simple Mastectomy
0,42,0.952560,2.15000,0.007972,-0.048340,1.0,0,0,0,0,1,0,0,1,0,0,0,1,0
1,54,0.000000,1.38020,-0.498030,-0.507320,1.0,0,0,0,1,1,0,0,1,0,0,0,1,0
2,63,-0.523030,1.76400,-0.370190,0.010815,1.0,0,0,0,0,1,0,0,1,0,1,0,0,0
3,78,-0.876180,0.12943,-0.370380,0.132190,1.0,0,0,0,0,1,0,1,0,0,0,0,1,0
4,42,0.226110,1.74910,-0.543970,-0.390210,1.0,0,0,1,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,59,0.024598,1.40050,0.024751,0.280320,1.0,0,0,1,0,1,0,0,1,0,1,0,0,0
330,41,0.100120,-0.46547,0.472370,-0.523870,1.0,0,0,1,0,1,0,1,0,0,0,1,0,0
331,54,0.753820,1.64250,-0.332850,0.857860,1.0,0,0,0,1,1,0,0,1,0,0,0,0,1
332,74,0.972510,1.42680,-0.366570,-0.107820,0.0,0,0,0,0,1,0,0,1,0,1,0,0,0
333,66,0.286380,1.39980,0.318830,0.836050,1.0,0,0,0,1,1,0,0,1,0,0,1,0,0

In [176]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

class DropMissing(BaseEstimator, TransformerMixin):
    """
    TODO make drop from specific columns work
    
    - if columns is None, every row with a missing value is dropped
    - if columns is a list, every row relating to a missing value in the list of columns is dropped
    
    >>> missing_yeeter = DropMissing(columns=['Patient_Status'])
    >>> missing_yeeter.transform(breast_cancer)
    """
    def __init__(self, columns=None) -> None:
        super().__init__()
        self.columns = columns

    def fit(self, X, y=None):
        return self
        
    def transform(self, X, y=None):
        # if self.columns is not None:
        #     X = X.dropna(subset=self.columns)
        # else:
        #     X = X.dropna()
        X = X.dropna() 
        return X
    
missing_yeeter = DropMissing()
please_please_work = missing_yeeter.transform(breast_cancer)

please_please_work

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.952560,2.15000,0.007972,-0.048340,II,1.0,0,0,0,Other,20-May-18,26-Aug-18,0
1,54,FEMALE,0.000000,1.38020,-0.498030,-0.507320,II,1.0,0,0,0,Other,26-Apr-18,25-Jan-19,1
2,63,FEMALE,-0.523030,1.76400,-0.370190,0.010815,II,1.0,0,0,0,Lumpectomy,24-Aug-18,08-Apr-20,0
3,78,FEMALE,-0.876180,0.12943,-0.370380,0.132190,I,1.0,0,0,0,Other,16-Nov-18,28-Jul-20,0
4,42,FEMALE,0.226110,1.74910,-0.543970,-0.390210,II,1.0,0,0,1,Lumpectomy,12-Dec-18,05-Jan-19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,59,FEMALE,0.024598,1.40050,0.024751,0.280320,II,1.0,0,0,1,Lumpectomy,15-Jan-19,27-Mar-20,0
330,41,FEMALE,0.100120,-0.46547,0.472370,-0.523870,I,1.0,0,0,1,Modified Radical Mastectomy,25-Jul-18,23-Apr-19,0
331,54,FEMALE,0.753820,1.64250,-0.332850,0.857860,II,1.0,0,0,0,Simple Mastectomy,26-Mar-19,11-Oct-19,1
332,74,FEMALE,0.972510,1.42680,-0.366570,-0.107820,II,0.0,0,0,0,Lumpectomy,26-Nov-18,05-Dec-18,0
333,66,FEMALE,0.286380,1.39980,0.318830,0.836050,II,1.0,0,0,0,Modified Radical Mastectomy,04-Feb-19,10-Aug-19,1

In [177]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

numeric_pipeline = Pipeline([
    ('drop_nans', DropMissing()),
    ('std_scaler', StandardScaler()),
    ('pca', PCA())
])

In [178]:
breast_cancer.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,II,1.0,0,0,0,Other,20-May-18,26-Aug-18,0
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,II,1.0,0,0,0,Other,26-Apr-18,25-Jan-19,1
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,II,1.0,0,0,0,Lumpectomy,24-Aug-18,08-Apr-20,0
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,I,1.0,0,0,0,Other,16-Nov-18,28-Jul-20,0
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,II,1.0,0,0,1,Lumpectomy,12-Dec-18,05-Jan-19,0

In [179]:
breast_cancer_columns

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,HER2 status,Surgery_type,Patient_Status
0,42,FEMALE,0.952560,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,Negative,Other,Alive
1,54,FEMALE,0.000000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,Negative,Other,Dead
2,63,FEMALE,-0.523030,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,Negative,Lumpectomy,Alive
3,78,FEMALE,-0.876180,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,Negative,Other,Alive
4,42,FEMALE,0.226110,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,Positive,Lumpectomy,Alive
...,...,...,...,...,...,...,...,...,...,...,...
329,59,FEMALE,0.024598,1.40050,0.024751,0.280320,II,Infiltrating Ductal Carcinoma,Positive,Lumpectomy,Alive
330,41,FEMALE,0.100120,-0.46547,0.472370,-0.523870,I,Infiltrating Ductal Carcinoma,Positive,Modified Radical Mastectomy,Alive
331,54,FEMALE,0.753820,1.64250,-0.332850,0.857860,II,Infiltrating Ductal Carcinoma,Negative,Simple Mastectomy,Dead
332,74,FEMALE,0.972510,1.42680,-0.366570,-0.107820,II,Infiltrating Lobular Carcinoma,Negative,Lumpectomy,Alive
333,66,FEMALE,0.286380,1.39980,0.318830,0.836050,II,Infiltrating Ductal Carcinoma,Negative,Modified Radical Mastectomy,Dead

In [183]:
from sklearn.compose import ColumnTransformer

USELESS_ATTRIBUTES = ['Date_of_Surgery', 'Date_of_Last_Visit', 'ER status', 'PR status']
breast_cancer_columns = breast_cancer.drop(USELESS_ATTRIBUTES, axis=1)

TARGET_ATTRIBUTE = 'Patient_Status'
NUM_ATTRIBUTES = ['Age', 'Protein1', 'Protein2', 'Protein3', 'Protein4']
CAT_ATTRIBUTES = ['Gender', 'Tumour_Stage', 'Surgery_type', 'Histology', 'HER2 status']

full_pipeline = ColumnTransformer([
    ('num', numeric_pipeline, NUM_ATTRIBUTES),
    ('cat', OneHotEncoder(), CAT_ATTRIBUTES),
])

prepared_breast_cancer_X = full_pipeline.fit_transform(breast_cancer_columns.drop(TARGET_ATTRIBUTE, axis=1))
pd.DataFrame(prepared_breast_cancer_X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,-1.573174,-0.135938,-1.720159,0.559023,0.877418,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
1,-0.454770,1.094776,-0.261139,0.251125,0.020051,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,-0.374348,0.731008,0.642998,-0.855045,0.291523,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.991502,0.187553,1.887669,-0.543110,-0.800104,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,-0.990936,1.108800,-1.214099,0.079969,0.055834,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,-0.377129,-0.324637,-0.031625,-0.335160,0.347895,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
330,1.615584,-0.059364,-1.609392,0.834097,-0.347015,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
331,-1.772126,-1.069364,-0.584320,-0.102611,-0.160986,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
332,-1.441735,-0.421297,0.708598,1.487114,0.323153,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
333,-0.602660,-1.488105,0.290004,-0.367695,0.537763,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

## Models

In [187]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    prepared_breast_cancer_X,
    breast_cancer[TARGET_ATTRIBUTE],
    test_size=0.2,
)

(67,)

In [199]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier()
forest_clf.fit(X_train, y_train)

RandomForestClassifier()

In [203]:
predictions = forest_clf.predict(X_test)
predictions[10:30], np.array(y_test[10:30])

(array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0]))